### ISSUE TITLE
Loosen dependency on rails (allow Rails 5.2)

### ISSUE THREAD

**Issue by rdunlop** [chiefpansancolt/simple_form_materialize#7]
## Expected Behavior

- I wish to be able to use this gem on rails 5.2

## Actual Behavior

- I cannot use rails 5.2 because it is locked to "rails < 5.2" in the gemfile

## Steps to Reproduce

- Try to use rails 5.2 and simple_form_materialize, "bundler" will fail to reconcile

## Browsers Used

- n/a

## OS Used
- [ ] Linux
- [x] Mac
- [ ] Windows

**Comment by chiefpansancolt** [comment]
loosened to allow to version 7 in version 1.2.0
